### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by maosuyun2009** [openhome/ohTopology#2]
when i run ./waf build
[13/16] cxxprogram: build/OpenHome/Av/Tests/TestTopology4.cpp.5.o -> build/TestTopology4
./libohTopology.a(CpTopology3.cpp.2.o): In function `OpenHome::Av::CpTopology3Group::EventVolumeLimitChanged()':
CpTopology3.cpp:(.text+0x190): undefined reference to`OpenHome::Net::CpProxyAvOpenhomeOrgVolume1::PropertyVolumeLimit(unsigned int&) const'
./libohTopology.a(CpTopology3.cpp.2.o): In function `OpenHome::Av::CpTopology3Group::EventMuteChanged()':

How Can i fix this error, Thanks

**Comment by SimonChisholm** [comment]
The code builds for me.  Have you run ./go fetch --all and ./waf configure ?  If so, can you provide a note of the output from configure and step [13/16] of your build with the -vv flag set please?

**Comment by maosuyun2009** [comment]
Yes, I have run ./go fetch --all and ./waf configure,This is my procedure:
./waf configure --ohnet=../ohNet --dest-platform=Linux-x86
Setting top to                           : /home/dennis/work/wifi_audio/openhome/ohTopology 
Setting out to                           : /home/dennis/work/wifi_audio/openhome/ohTopology/build 
debugmode:                               : Release 
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Setting INCLUDES_OHNET to                : /home/dennis/work/wifi_audio/openhome/ohNet/Build/Include 
Setting STLIBPATH_OHNET to               : /home/dennis/work/wifi_audio/openhome/ohNet/Build/Obj/Posix/Release 
'configure' finished successfully 0.038s

./waf build -v
Waf: Entering directory `/home/dennis/work/wifi_audio/openhome/ohTopology/build'
[13/18] cxxprogram: build/OpenHome/Av/Tests/TestTopology3.cpp.5.o -> build/TestTopology3
23:25:02 runner ['/usr/bin/g++', '-pthread', 'OpenHome/Av/Tests/TestTopology3.cpp.5.o', '-o', '/home/dennis/work/wifi_audio/openhome/ohTopology/build/TestTopology3', '-Wl,-Bstatic', '-L.', '-L/home/dennis/work/wifi_audio/openhome/ohNet/Build/Obj/Posix/Release', '-lohTopology', '-lohNetProxies', '-lTestFramework', '-lohNetCore', '-Wl,-Bdynamic']
./libohTopology.a(CpTopology3.cpp.2.o): In function`OpenHome::Av::CpTopology3Group::EventVolumeLimitChanged()':
CpTopology3.cpp:(.text+0x190): undefined reference to `OpenHome::Net::CpProxyAvOpenhomeOrgVolume1::PropertyVolumeLimit(unsigned int&) const'
./libohTopology.a(CpTopology3.cpp.2.o): In function`OpenHome::Av::CpTopology3Group::EventMuteChanged()':
................
.................
Waf: Leaving directory `/home/dennis/work/wifi_audio/openhome/ohTopology/build'
Build failed
 -> task in 'TestTopology3' failed (exit status 1): 
        {task 152248716: cxxprogram TestTopology3.cpp.5.o -> TestTopology3}
['/usr/bin/g++', '-pthread', 'OpenHome/Av/Tests/TestTopology3.cpp.5.o', '-o', '/home/dennis/work/wifi_audio/openhome/ohTopology/build/TestTopology3', '-Wl,-Bstatic', '-L.', '-L/home/dennis/work/wifi_audio/openhome/ohNet/Build/Obj/Posix/Release', '-lohTopology', '-lohNetProxies', '-lTestFramework', '-lohNetCore', '-Wl,-Bdynamic']

**Comment by SimonChisholm** [comment]
I can't reproduce this - the build works fine for me.

I notice that TestTopology3.cpp is job 13 out of 18 for you.  It is [15/24] using the latest source.  Possibly you don't have the latest source or your wscript is out of date?

Another possibility - mono is required for code generation early in the build.  Have you edited your wscript to try to avoid this?
