### ISSUE TITLE
Do not generate CpAvOpenhomeOrgProduct1 and CpAvOpenhomeOrgVolume1

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohTopology#8]
Both files are part of ohNetGenerated. This removes the dependency of having mono available on the host system which is a heavy dependency when cross-compiling in Buildroot. Furthermore, it allows to build the static library much faster.

**Comment by SimonChisholm** [comment]
I wouldn't be keen to add a dependency on ohNetGenerated.  It is a legacy repo that only exists to support the few client libraries too primitive to handle the dependency checking needed to generate their own code.  I do agree that mono is a substantial dependency just for a small amount of code generation however.  We'd like to replace use of the C# T4 tool with a python script.  There are no firm timescales for this work unfortunately.

**Comment by joerg-krause** [comment]
@SimonChisholm I didn't know that ohNetGenerated is legacy. I've seen that *CpAvOpenhomeOrgProduct1* is part of *ohNet*, but *CpAvOpenhomeOrgVolume1* isn't. This issue could also be solved, if the latter would be included in *ohNet*, too, so that *ohTopology* depends on *ohNet* instead.
